services:
  nebula-sync:
    image: ${NEBULA_IMAGE}:${NEBULA_TAG}
    container_name: ${NEBULA_NAME}
    environment:
      - PRIMARY=${NEBULA_PRIMARY}
      - REPLICAS=${NEBULA_REPLICAS}
      - FULL_SYNC=${NEBULA_FULL_SYNC}
      - RUN_GRAVITY=${NEBULA_RUN_GRAVITY}
      - CRON=${NEBULA_CRON}
