services:
  portainer:
    image: ${PORTAINER_IMAGE}:${PORTAINER_TAG}
    container_name: ${PORTAINER_NAME}
    hostname: ${PORTAINER_HOSTNAME}
    restart: unless-stopped
    networks:
      macvlan_network:
        ipv4_address: ${PORTAINER_IP}
    ports:
      - "${PORTAINER_PORT_EDGE}:8000"
      - "${PORTAINER_PORT_HTTP}:9000"
      - "${PORTAINER_PORT_HTTPS}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA_PATH}:/data
    environment:
      - TZ=${TZ}
    labels:
      caddy: ${PORTAINER_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 9000}}"
      caddy.tls: ${CADDY_TLS}
    healthcheck:
      test: "nc -z -v localhost 9000 || exit 1"
      interval: ${HEALTH_INTERVAL}
      timeout: ${HEALTH_TIMEOUT}
      retries: ${HEALTH_RETRIES}

networks:
  macvlan_network:
    external: true
